/**
 * Reservation Api
 * Reservation Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateReservationRequestDto { 
    /**
     * Room to be reserved
     */
    roomNumber?: number;
    /**
     * Start Date of recurring events period. If Single Event just date of reservation. End date empty then
     */
    beginDate?: string;
    /**
     * End Date of recurring events period. If Single Event it's the same as begin date.
     */
    endDate?: string;
    /**
     * Start time of reservation slot
     */
    beginTime?: string;
    /**
     * Start time of reservation slot
     */
    endTime?: string;
    /**
     * Days of reservation. 1 - MON, 2 - THU ...
     */
    daysOfWeek?: Array<number>;
}