/**
 * Reservation Api
 * Reservation Api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SingleReservationDto { 
    /**
     * Id of reservation entity which was base for creation this particular instance. Used for deleting reservations.
     */
    reservationId?: number;
    /**
     * User who made reservation
     */
    userNick?: string;
    /**
     * Date of day of reservation
     */
    date?: string;
    /**
     * Begin time of reservation
     */
    beginTime?: string;
    /**
     * Begin time of reservation
     */
    endTime?: string;
}